### ISSUE TITLE
Systems Talk: Hot Partitions & Load Variance in Distributed Systems

### ISSUE THREAD

**Issue by eightnoteight** [zigindia/talk-proposal#2]
## Hot Partitions & Load Variance in Distributed Systems
**Duration**: 45 minutes

Covering stories about what leads to load variance in various distributed systems, the behavior it shows when it happens, and finally how to avoid and handle production incidents.

### Simple Cases
* CPU Hot Partition Stories
* Memory Hot Partition Stories
* Disk Hot Partition Stories
* Network Hot Partition Stories

### Complicated Cases

* Load Variance in Persistent Connection Systems
    * WebSocket Connections
    * gRPC Connections
    * HTTP Persistent Connections
    * MQTT Persistent Connections
    * Control Plane / Data Plane (Istio / Kong, etc.)
    * Multi-Proxy Layers
    * Load Variance in Network Load Balancers

* Load Variance in Application Workloads
    * Kafka Consumer Groups
    * In-App Pub/Sub
    * In-App Cron Job Libraries
        * Celery
        * Sidekiq
        * Gocron
    * Load Variance Due to Noisy Neighbors

* Hot Writer in Writer/Reader Replication Systems

* Hot Leader in Consensus-Based Distributed Systems

### Takeaways

* Techniques & Solutions to Avoid Load Variance & Hot Partition Incidents

### References

- TODO: I will add the slides 4-5 days in advance.

**Comment by srijan-paul** [comment]
Thanks for the submission!

This looks great.
Since the next meetup is just two hours and we already have the RISC-V talk,
I think we can present this in a few ways:

1. Present on October meetup, but with a shorter duration (preferably 25).
2. Present online on Discord/Zoom, for as long as you'd like the session to be.
3. Present in a future meetup (next one is most likely November), for ~40-45 minutes.

Do you think either of these options would work for you?

**Comment by eightnoteight** [comment]
thanks for providing all the options

option 1 sounds good 👍 , I'll fine-tune the content to 25 minutes at max

**Comment by srijan-paul** [comment]
Gotcha. See you at the meetup then.
Let us know once you have the slides :)

**Comment by eightnoteight** [comment]
thanks @srijan-paul, as discussed I'll close the issue for now :)
